feat: activate/deactivate user api
aws-solutions/solution-spark-on-aws pull request #553
Opened 2022-10-18 22:04 UTC by bhudnell

Issue #, if available:

Description of changes:

Checklist:

* [ ] Have you successfully deployed to an AWS account with your changes?
* [ ] Have you written new tests for your core changes, as applicable?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-19 20:01 UTC, DaveMadsen commented on workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
> +  public constructor(userPoolId: string, aws: AwsService) {
Breaking change? Are you sure you've hit all of the callers in our repo?
Please add a note to the Readme that indicates the version number rev where the breaking change occurs and the course of action to be taken to fix it.

2022-10-19 20:02 UTC, DaveMadsen requested changes
This looks like a breaking change. Please document it in the appropriate `README.md`.

2022-10-19 23:40 UTC, kpark277 approved these changes

2022-10-20 16:44 UTC, DaveMadsen approved these changes

2022-10-20 16:48 UTC, kpark277 approved these changes

2022-10-20 16:50 UTC, merged