fix(utilities): refactor utilities, add tests, typo fixes
aws-solutions/solution-spark-on-aws pull request #592
Opened 2022-11-02 21:03 UTC by maghirardelli

Issue #, if available:

Description of changes:
refactor utilities for pagination and dynamoDBService and services that consume them
add tests for DynamoDB
fix small typos

Checklist:

* [x] Have you successfully deployed to an AWS account with your changes?
* [x] Have you written new tests for your core changes, as applicable?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-02 21:40 UTC, aws-tyler requested changes
Your code looks great. A potential vuln was found though, so marking as `Request Changes` until we decide whether to fix it or leave it as is for now to keep us unblocked. If we leave it for now we need to make a ticket to go back and fix ASAP.

2022-11-02 22:33 UTC, bhudnell approved these changes
Looks like the CodeQL alert is a false positive to me. I'm guessing that it saw `params` and assumed it was from a request object liek `req.params.variableName`

2022-11-02 23:23 UTC, FernandoAranda approved these changes

2022-11-02 23:26 UTC, FernandoAranda commented on workbench-core/base/src/constants/queryParams.ts
> +import { AttributeValue } from '@aws-sdk/client-dynamodb';
this will affect the changes for filter and sort, I will set a reminder for myself to check this after merging our common code

2022-11-03 04:54 UTC, nguyen102 commented
> Your code looks great. A potential vuln was found though, so marking as `Request Changes` until we decide whether to fix it or leave it as is for now to keep us unblocked. If we leave it for now we need to make a ticket to go back and fix ASAP.

To resolve the security vulnerability, we can check the length of `params.datasetIds` and make sure it's less than N items. DDB query can only return 1 MB of data so if there's too many `datasetIds` we would need to query DDB repeatedly. We can check how much space an additional `datasetId` requires (for each datasetId, we pull the dataset record from DDB [here](https://github.com/aws-solutions/solution-spark-on-aws/pull/592/files#diff-f1abf758c3206eeb07deec5194b081e75de50255015a900efcd2f07a7a038448R384) and set N appropriately. If `datasetIds` is larger than N we can throw a `Boom.badRequest` error.

2022-11-03 12:47 UTC, maghirardelli commented
I fixed the CodeQL Warning: https://github.com/aws-solutions/solution-spark-on-aws/security/code-scanning/49. @aws-tyler can you unblock this PR and approve?

2022-11-03 12:53 UTC, aws-tyler approved these changes

2022-11-03 13:27 UTC, DaveMadsen approved these changes

2022-11-03 13:29 UTC, merged