Topic: addUserToGroup method implementation
aws-solutions/solution-spark-on-aws pull request #705
Opened 2022-12-16 16:53 UTC by otlci

Issue #, if available: MAFoundation-517

Description of changes:

This PR adds implementation of addUserGroup method in Workbench Core User Management Service

*Note:* Requires https://github.com/aws-solutions/solution-spark-on-aws/pull/700 to be merged first

Checklist:

* [x] Have you written new tests for your core changes, as applicable?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-16 17:44 UTC, DaveMadsen requested changes
Please implement the addUsertoGroup method in `DynamicAuthorizationService` and write a couple of integration tests.

2022-12-16 22:00 UTC, DaveMadsen approved these changes

2022-12-19 19:08 UTC, bhudnell commented on workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
> +    return this._groupManagementPlugin.addUserToGroup(addUserToGroupRequest);
I believe we need to check if `groupStatus === 'active'` to make sure we can add the user to the group. @htztomic can you confirm?

2022-12-19 19:10 UTC, bhudnell commented on workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
> +  // Get auth provider's login URL with temporary state and PKCE strings
I dont think this comment belongs here 😃

2022-12-21 17:34 UTC, closed without merging